### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mschmieder** [cirruslabs/gitlab-tart-executor#10]
The documentation should be improved to better clarify on

- current functionality
- current limitations

**Comment by edigaryev** [comment]
Hello Matthias!

There were a couple of updates to the [`README.md`](https://github.com/cirruslabs/gitlab-tart-executor/blob/main/README.md) since this issue was created.

Could you please provide some concrete examples of the current functionality and limitations that you find in need of clarification?

**Comment by waddles** [comment]
```prepare_args = ["prepare", "--concurrency 2", "--cpu auto", "--memory auto"]```
should be
```prepare_args = ["prepare", "--concurrency", "2", "--cpu", "auto", "--memory", "auto"]```

**Comment by waddles** [comment]
We also need some documentation on the use of cache dir. Reading the MR is quite confusing but if I understand correctly, I need to set the path in `config_args` as well as the `cache_dir`* value, for example:
```toml
[[runners]]
  executor = "custom"
  builds_dir = "/Users/admin/builds"
  cache_dir = "/Users/admin/cache"
  [runners.custom]
    config_exec = "gitlab-tart-executor"
    config_args = ["config", "--cache-dir", "/Users/admin/cache"]
  [runners.environment]
    # force all jobs to use a temp dir mounted from the host as `builds_dir`
    TART_EXECUTOR_HOST_DIR = true
    # host `--cache-dir` always gets mounted as `/Volumes/My Shared Files/cachedir` inside VM
    #TART_EXECUTOR_INTERNAL_CACHE_DIR = "/Volumes/My Shared Files/cachedir"
```
I don't understand why you couldn't use the `runners.cache_dir` path to append args in the config stage, then the environment variable could just be `TART_EXECUTOR_SHARED_CACHE_DIR = "true"`. Is that because `gitlab-runner` does not pass that config through to `gitlab-tart-executor`?

[* according to docs](https://docs.gitlab.com/runner/executors/custom.html)
> In addition both `builds_dir` and `cache_dir` inside of the [[[runners]]](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-section) are required fields.
