### ISSUE TITLE
Gitlab CI + pull from registry = 403 AuthFailed error

### ISSUE THREAD

**Issue by micho233** [cirruslabs/gitlab-tart-executor#101]
I have an AWS macOS instance that I am using for building macOS images. I am also using the same instance as a GitLab runner host to pull images and run VMs by using a custom GitLab runner and gitlab-runner-executor.

This is the job I am using to push the macOS image to the GitLab registry:

```
macos-15-xcode-16-upload:
  stage: upload
  extends:
    - .rules:default_branch
    - .macos-15_options
  needs:
    - xcode-certs
  script:
    - export TART_REGISTRY_HOSTNAME=$CI_REGISTRY
    - export TART_REGISTRY_USERNAME=$CI_REGISTRY_USER
    - export TART_REGISTRY_PASSWORD=$CI_JOB_TOKEN
    - tart push macos-15-xcode-16 $CI_REGISTRY_IMAGE/macos-15-xcode-16:latest --chunk-size 4 --concurrency 1
```

Pushing images works well, but pulling images doesn’t work:

```
test:
  image: ${CI_REGISTRY}/engineering/macos-images/macos-15-xcode-16:latest
  tags:
    - aws-m2-macos-vm
  script:
    - uname -a

```

It throws an error:

```
Using Custom executor...
[6](https://self-hosted-gitlab.xxx/engineering/mobile/ios/ios-app/-/jobs/10371671#L6)2025/01/24 12:58:09 Pulling the latest version of self-hosted-gitlab.xxx/engineering/macos-images/macos-15-xcode-16:latest...
[7](https://self-hosted-gitlab.xxx/engineering/mobile/ios/ios-app/-/jobs/10371671#L7)2025/01/24 12:58:09 tart command returned non-zero exit code: "Error: AuthFailed(why: \"received unexpected HTTP status code 403 while retrieving an authentication token\", details: \"{\\\"errors\\\":[{\\\"code\\\":\\\"DENIED\\\",\\\"message\\\":\\\"access forbidden\\\"}],\\\"http_status\\\":403}\")"
```

I thought it was because the registry credentials are stored in the keychain during the push job, but after removing the keychain credentials, the error is still the same.

**Comment by micho233** [comment]
I was following this guideline to implement push by authenticating using CI_JOB_TOKEN: https://docs.gitlab.com/ee/user/packages/container_registry/authenticate_with_container_registry.html

Since I have GitLab variables defined like this:
```
variables:
  TART_REGISTRY_HOSTNAME: $CI_REGISTRY
  TART_REGISTRY_USERNAME: $CI_REGISTRY_USER
  TART_REGISTRY_PASSWORD: $CI_JOB_TOKEN
```
I didn’t expect that I would need to call tart login before pulling an image, similar to tart push where I didn’t call login before pushing an image.
