### ISSUE TITLE
Failed to upload job artifacts

### ISSUE THREAD

**Issue by ademyanets** [cirruslabs/gitlab-tart-executor#117]
Hi guys

I'm facing with problem when tried to upload artifacts. Log ends with:
```
Uploading artifacts for successful job
Missing gitlab-runner. Uploading artifacts is disabled.
Cleaning up project directory and file based variables
Job succeeded
```
Do I miss something? I haven't found any notes about artifact uploading. Do I need to install ordinary gitlab-runner into my image? Or artifacts must work transparently from gitlab-tart-executor with no additional configuration?

**Comment by ademyanets** [comment]
So, I have Mac with configured GitLab Runner and gitlab-tart-executor, I run job using tart image to build my project. And to make possible to upload artifact I need to install gitlab-runner into my image. But how in this case it should be configured?

**Comment by ademyanets** [comment]
Looks like this is not the case. I added _gitlab-runner -v_ to the end of my pipeline script:

```
Version:      17.11.1
Git revision: 96856197
Git branch:   17-11-stable
GO version:   go1.24.2
Built:        2025-05-05T10:24:25+00:00
OS/Arch:      darwin/arm64

Uploading artifacts for successful job
Missing gitlab-runner. Uploading artifacts is disabled.
Cleaning up project directory and file based variables
Job succeeded

```
My brew installed gitlab-runner is on the board and brew is in $PATH. I suppose in this case I need to configure nested gitlab-runner in my VM, but how?

**Comment by edigaryev** [comment]
Just checked, and artifact uploading works fine with the following GitLab CI configuration:

```yaml
macos_job:
  image: ghcr.io/cirruslabs/macos-sequoia-base:latest

  script: |
    mkdir output
    echo "Hello, world!" > output/hello.txt

  artifacts:
    paths:
      - output/

variables:
  TART_EXECUTOR_ALWAYS_PULL: "false"
  TART_EXECUTOR_INSTALL_GITLAB_RUNNER: "brew"

```

1. Can you try the same with the Cirrus Labs provided image, such as `ghcr.io/cirruslabs/macos-sequoia-base:latest`?

1. How does your GitLab CI configuration look like?

1. How does your GitLab Runner configuration look like?
