### ISSUE TITLE
setting TART_EXECUTOR_HOST_DIR: true yields "A directory sharing device configuration is invalid."

### ISSUE THREAD

**Issue by macrozone** [cirruslabs/gitlab-tart-executor#35]
basically the issue in the title. 

Both host and vm are ventura, so TART_EXECUTOR_HOST_DIR should work according to the docs.

Any idea what's wrong?

update: host is ventura 13.5 and vm is ventura 13.4

**Comment by fkorotkov** [comment]
Do you use Ventura prior to 13.3 version by any chance? Mounting volumes  started working more or less stable in Ventura starting with 13.3.

**Comment by macrozone** [comment]
> Do you use Ventura prior to 13.3 version by any chance? Mounting volumes started working more or less stable in Ventura starting with 13.3.

no, host is ventura 13.5 and the vm is ventura 13.4 (its currently based on ghcr.io/cirruslabs/macos-ventura-xcode, but i adjusted it using packer)

**Comment by edigaryev** [comment]
1. Which Tart version are you running?

2. Are there other Tart-specific settings that you use in GitLab Runner's `config.toml` (specifically, `{config,prepare,run,cleanup}_args` in `[runners.custom]` section) or in `.gitlab-ci.yml` (specifically, those starting with `TART_*`)? 

3. Could you try minimizing your example down to using a non-customized and publicly available image like `ghcr.io/cirruslabs/macos-ventura-base:latest` and share your `.gitlab-ci.yml` here?

    Because the following `.gitlab-ci.yml` works just fine for me on macOS 13.5 (host) and Tart 1.9.2:

    ```yaml
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
    
    job:
      script:
        - uname -a
    
    variables:
      TART_EXECUTOR_ALWAYS_PULL: "false"
      TART_EXECUTOR_HOST_DIR: "true"
    ```
