### ISSUE TITLE
A canceled GitLab CI job does not stop the tart runner VM

### ISSUE THREAD

**Issue by rgl** [cirruslabs/gitlab-tart-executor#36]
When we cancel a GitLab CI job from the GitLab UI, the tart VM is not destroyed.

Accordingly to the [GitLab documentation](https://docs.gitlab.com/runner/executors/custom.html#terminating-and-killing-executables), GitLab will call the `cleanup_exec` to terminate/cleanup the runner when a job is canceled. Maybe this tart executor is not handling that part as a forcefully destroy the VM?

For reference, this is how gitlab tart runner is configured:

```toml
[[runners]]
  name = "tart"
  url = "https://git.example.com"
  id = 166
  token = "xxx"
  token_obtained_at = 2023-08-29T12:23:35Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "custom"
  builds_dir = "/builds"
  cache_dir = "/cache"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.custom]
    config_exec = "/opt/homebrew/bin/gitlab-tart-executor"
    config_args = ["config"]
    config_exec_timeout = 120
    prepare_exec = "/opt/homebrew/bin/gitlab-tart-executor"
    prepare_args = ["prepare", "--concurrency", "2", "--cpu", "auto", "--memory", "auto"]
    prepare_exec_timeout = 120
    run_exec = "/opt/homebrew/bin/gitlab-tart-executor"
    run_args = ["run"]
    cleanup_exec = "/opt/homebrew/bin/gitlab-tart-executor"
    cleanup_args = ["cleanup"]
    cleanup_exec_timeout = 120
```
