### ISSUE TITLE
TART_EXECUTOR_ALWAYS_PULL still clones the image again and creates a new VM

### ISSUE THREAD

**Issue by riain0** [cirruslabs/gitlab-tart-executor#41]
Hi there,

I'm using the following versions:

- Gitlab Runner v16.5.0
- macOS Ventura 13.3 (running on EC2)
- Latest versions of `tart` and `gitlab-tart-executor`.

I may be misunderstanding the documentation but when using `TART_EXECUTOR_ALWAYS_PULL` and it is set to `false`, I expect it to use the image which would've been pulled down in a previous job, which runs on the same macOS host instance as it is on EC2 and is using AWS dedicated hosts. However, what I see if the following logs, in a new job directly after a passing one previously.

```
Running with gitlab-runner 16.5.0 (853330f9)
  on instance X
Resolving secrets
Preparing the "custom" executor
Using Custom executor...
2023/11/02 14:37:0[5] Cloning and configuring a new VM..
```

Our Gitlab pipeline definition is incredibly simple:

```yaml
variables:
    TART_EXECUTOR_ALWAYS_PULL: "false"

run macos:
    image: <internal ECR mirror>/macos-ventura-xcode:15
    script:
        - echo test
    tags:
        - mac-arm64
```

The runner toml is pretty standard too:

```toml
listen_address = ":8083"
concurrent = 4
check_interval = 0
log_format = "json"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "<instance id>"
  output_limit = 20480
  url = "<url>"
  id = 1197945
  token = ""
  token_obtained_at = 2023-11-01T11:58:23Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "custom"
  builds_dir = "/Users/ec2-user/gitlab/builds"
  cache_dir = "/Users/ec2-user/gitlab/cache"
  environment = ["GITLAB_V2=true"]
  [runners.cache]
    Type = "s3"
    Shared = true
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
      ServerAddress = "s3.amazonaws.com"
      BucketName = "<s3 bucket>"
      BucketLocation = "eu-central-1"
  [runners.custom]
    prepare_exec = "gitlab-tart-executor"
    prepare_args = ["prepare"]
    run_exec = "gitlab-tart-executor"
    run_args = ["run"]
    cleanup_exec = "gitlab-tart-executor"
    cleanup_args = ["cleanup"]
    config_exec = "gitlab-tart-executor"
    config_args = ["config", "--cache-dir", "/Users/ec2-user/gitlab/cache", "--builds-dir", "/Users/ec2-user/gitlab/builds"]
```

I'm not sure where I am going wrong here... even this simple pipeline takes ~20 minutes to run as it downloads the image each time.
