### ISSUE TITLE
Support for block devices as builds/cache dirs

### ISSUE THREAD

**Issue by jlsalmon** [cirruslabs/gitlab-tart-executor#60]
Would it be possible to add support to the gitlab executor for using block devices? Specifically I would like to try using a block device as the builds/cache dirs (since virtiofs mounts via `--builds-dir` and `--cache-dir` don't currently work due to cirruslabs/tart#567).

I'm not sure how this would work with the requirement to run tart as root when attaching block devices though.

**Comment by fkorotkov** [comment]
We can probably add support for passing block devices via `--builds-dir` and `--cache-dir`. Might be a bit tricky to map such mounts inside the VM especially if both `--builds-dir` and `--cache-dir` are specified.

**Comment by edigaryev** [comment]
Hello Justin 👋 

Have you considered [using a distributed cache](https://docs.gitlab.com/runner/configuration/speed_up_job_execution.html#use-a-distributed-cache) instead?

It works just as snappy as a mounted directory/block device, but without the mounted directory bugs and extra complexity of managing the block devices (namely, Tart process running with elevated privileges, filesystem corruption due to concurrent access from multiple jobs, etc).

Here's a quick example snippet that once put in `~/.gitlab-runner/config.tom`, will cache everything to `minio server /path/to/a/directory` (assuming that it's accessible on `minio.local`):

```toml
[[runners]]
  [runners.cache]
    Type = "s3"
    [runners.cache.s3]
      ServerAddress = "minio.local:9000" 
      AccessKey = "minioadmin"
      SecretKey = "minioadmin"
      BucketName = "gitlab-cache"
      Insecure = true
```
