### ISSUE TITLE
Allow to login to private OCI registries through CI Variables

### ISSUE THREAD

**Issue by mschmieder** [cirruslabs/gitlab-tart-executor#7]
The executor should support logging into a private registry by defining CI Variables.

Oftentimes you might want to provide your own OCI-compliant images created with [Packer](https://www.packer.io/) and the official [Tart Builder](https://developer.hashicorp.com/packer/plugins/builders/tart). If you push your images to a private registry you will need to provide the credentials for the to login there first.

The following job definition should work to pull images from different registries for each job by setting

`TART_REGISTRY_USERNAME`
`TART_REGISTRY_PASSWORD`
`TART_REGISTRY`

```yaml
stages:
 - build

variables:
    TART_REGISTRY_USERNAME: myuser@myregistry.com
    TART_REGISTRY_PASSWORD: <some_secret>
    TART_REGISTRY: private.registry.io

job1:
  image: private.registry.io/tart/xcode14:latest
  stage:
    - build
  tags:
    - tart
  before_script:
    - brew install gitlab-runner # you will need to make sure `gitlab-runner` executable is available to be able to upload artifacts
  script:
    - echo "This is brought to you by tart" >> artifact.txt
  artifacts:
    paths:
      - artifact.txt

job2:
  image: private.other.io/tart/xcode14:latest
  variables:
    # override the OCI login information for this job only
    TART_REGISTRY_USERNAME: myuser@other.com
    TART_REGISTRY_PASSWORD: <some_secret>
    TART_REGISTRY: private.other.io
  stage:
    - build
  tags:
    - tart
  script:
    - echo "This is brought to you by tart" >> artifact.txt
 ```
