### ISSUE TITLE
Concurrent `--cache-dir` mount failing?

### ISSUE THREAD

**Issue by olejnjak** [cirruslabs/gitlab-tart-executor#73]
👋 guys,

I wanted to consult a one thing. It is a few days we are experiencing some weird issues on our CI, mainly it seems to have something to do with mounting the cache dir when concurrent jobs get to mount it in about the same time. 

I think the only change that occurred on our host machine could be OS update from 14.3 to 14.4.1, guest images are the same. I updated Gitlab Runner, Gitlab Tart Executor and Tart as an attempt to fix that, but without any success.

Our tart tooling should be currently up to date:
```sh
 ~ % brew list --versions
gitlab-runner 16.10.0
gitlab-tart-executor 1.13.0
softnet 0.10.1
tart 2.8.1
```

Our runner config:
```toml
concurrent = 2
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "<...>"
  url = "https://gitlab.<...>"
  id = 834
  token = "<...>"
  token_obtained_at = <...>
  token_expires_at = <...>
  executor = "custom"
  environment = ["MINT_PATH=/Volumes/My Shared Files/mint", "MINT_LINK_PATH=/Volumes/My Shared Files/mint/bin", "TUIST_CACHE_PATH=/Volumes/My Shared Files/TuistCache"]
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.feature_flags]
    FF_RESOLVE_FULL_TLS_CHAIN = false
  [runners.custom]
    config_exec = "gitlab-tart-executor"
    config_args = ["config", "--cache-dir", "/Users/user/Library/Caches/GitlabCI/cache"]
    prepare_exec = "gitlab-tart-executor"
    prepare_args = ["prepare", "--concurrency", "2", "--cpu", "auto", "--memory", "auto", "--dir", "mint:/Users/user/.mint", "--dir", "TuistCache:/Users/user/.tuist/Cache"]
    run_exec = "gitlab-tart-executor"
    run_args = ["run"]
    cleanup_exec = "gitlab-tart-executor"
    cleanup_args = ["cleanup"]
```

Executor creates different VMs correctly:
```sh
 ~ % tart list              
Source Name  Disk Size State  
local  gitlab-3331894 80   62   running
local  gitlab-3331895 80   62   running
```

In our environment there is nothing Tart related.

The errors we are getting look like this
```sh
Running with gitlab-runner 16.10.0 (81ab07f6)
  on <...>, system ID: <...>

Preparing the "custom" executor
Using Custom executor...
2024/04/12 01:48:57 Pulling the latest version of ghcr.io/ackeecz/ackee-xcode:latest...
2024/04/12 01:48:58 Cloning and configuring a new VM...
2024/04/12 01:48:58 Waiting for the VM to boot and be SSH-able...
2024/04/12 01:49:12 Was able to SSH!
2024/04/12 01:49:12 Mounting cachedir...
2024/04/12 01:49:12 ssh: unexpected packet in response to channel open: <nil>
ERROR: Job failed: exit status 1
```

```sh
Running with gitlab-runner 16.10.0 (81ab07f6)
  on <...>, system ID: <...>

Preparing the "custom" executor
Using Custom executor...
2024/04/12 02:01:52 Pulling the latest version of ghcr.io/ackeecz/ackee-xcode:latest...
2024/04/12 02:01:53 Cloning and configuring a new VM...
2024/04/12 02:01:53 Waiting for the VM to boot and be SSH-able...
2024/04/12 02:02:07 Was able to SSH!
2024/04/12 02:02:07 Mounting cachedir...
mount_virtiofs: failed to mount /Users/admin/cachedir: Resource busy
2024/04/12 02:02:08 Process exited with status 75
ERROR: Job failed: exit status 1
```

I think that maybe SSH config might be relevant, but there is nothing interesting:
```
~ % cat .ssh/config 
Host *
  UseKeychain yes
  ServerAliveInterval 120
  TCPKeepAlive no
```

Do you have any idea what the cause could be? We are not struggling with disk space, the host machine has over 350 GB disk space left so it should not be an issue. I don't think that using `(CUSTOM_ENV_)CI_CONCURRENT_ID` variable in cachedir path is a solution as I do want concurrent jobs to share the cache.

Thanks in advance :-) 

EDIT: Maybe good to know, that when I was running CI on my personal Macbook with the same setup, just more boilerplate stuff in system as it is not used only for CI (unline our Mac Mini that has this issue), everything ran just fine. When I disable concurrent jobs everything seems to run just fine. Machine restart did not help.

**Comment by fkorotkov** [comment]
Thank you for the detailed report! This part is the most concerning:

> mount_virtiofs: failed to mount /Users/admin/cachedir: Resource busy

VirtioFS works via builtin VirtioFS server/client in macOS. Host is running a server instance and guests connect to it. So an OS update either on host or guest can affect this behaviour.

Which macOS version does you guest use? How frequently this behaviour happens?

I tried to reproduce it with two VMs running 14.4.1 and host on 14.4.1 but with no luck. Mounting worked. PS I didn't even think that mounting a single folder into two VMs works 😅

**Comment by olejnjak** [comment]
> Which macOS version does you guest use?

Guests used 14.3.1, but I am not sure if it is relevant as on my Mac with the same setup (same OS same tooling version) and exactly the same guest images it works just fine. I just updated our guests to 14.4.1 so will try with that. 

> How frequently this behaviour happens?

On the affected machine it was almost like 4/5 times as our pipelines start with 2 or 3 concurrent jobs.

> I tried to reproduce it with two VMs running 14.4.1 and host on 14.4.1 but with no luck. Mounting worked. PS I didn't even think that mounting a single folder into two VMs works 😅

I have not configured it this way intensionally, just did it somehow and it worked for months 😂 It would actually make sense if it did not, but that might be a shame as I think that sharing it among VMs actually makes a good sense.

I am thinking if the executor couldn't rsync the cachedir to unique location (I guess in prepare stage) and in cleanup stage rsync it back, but that would of course mean introducing some locks and sync stuff which is not that simple 🤔

**Comment by edigaryev** [comment]
You might also [consider using S3 cache](https://github.com/cirruslabs/gitlab-tart-executor/issues/60#issuecomment-1943498523) as an alternative to the `Virtualization.Framework`'s directory sharing as the former is notorious for random errors, especially under load, see https://github.com/cirruslabs/tart/issues/567.

**Comment by olejnjak** [comment]
Hi @edigaryev @fkorotkov,

Okay I just encountered the same `Resource busy` error on my Macbook running macOS 14.4.1 and 14.4.1 guest image. I will accompany concurrent ID to our cache dir path.

If it is not meant to be shared among concurrent executions, I think we can close this issue.  But maybe it might be worth documenting? Also for `--builds-dir` but it is more obvious for that case.

**Comment by olejnjak** [comment]
Okay, now it becomes interesting...

I am getting resource busy error even without shared cache dir 😬 

```sh
Running with gitlab-runner 16.10.0 (81ab07f6)
  on <...>, system ID: <...>

Preparing the "custom" executor
Using Custom executor...
2024/04/23 00:36:24 Pulling the latest version of ghcr.io/AckeeCZ/ackee-xcode:latest...
2024/04/23 00:36:25 Cloning and configuring a new VM...
2024/04/23 00:36:25 Waiting for the VM to boot and be SSH-able...
2024/04/23 00:36:33 Was able to SSH!
2024/04/23 00:36:33 Mounting cachedir...
mount_virtiofs: failed to mount /Users/admin/cachedir: Resource busy
2024/04/23 00:36:33 Process exited with status 75
ERROR: Job failed: exit status 1
```

`~/.gitlab-runner/config.toml`
```toml
concurrent = 2
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "<...>"
  url = "<url>"
  id = 834
  token = "<token>"
  token_obtained_at = <date>
  token_expires_at = <date>
  executor = "custom"
  environment = ["MINT_PATH=/Volumes/My Shared Files/mint", "MINT_LINK_PATH=/Volumes/My Shared Files/mint/bin", "TUIST_CACHE_PATH=/Volumes/My Shared Files/TuistCache"]
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.feature_flags]
    FF_RESOLVE_FULL_TLS_CHAIN = false
  [runners.custom]
    config_exec = "gitlab-tart-executor"
    config_args = ["config", "--cache-dir", "/Users/user/Library/Caches/GitlabCI/cache/$CUSTOM_ENV_CI_CONCURRENT_PROJECT_ID"]
    prepare_exec = "gitlab-tart-executor"
    prepare_args = ["prepare", "--concurrency", "2", "--cpu", "auto", "--memory", "auto", "--dir", "mint:/Users/user/.mint", "--dir", "TuistCache:/Users/user/.tuist/Cache"]
    run_exec = "gitlab-tart-executor"
    run_args = ["run"]
    cleanup_exec = "gitlab-tart-executor"
    cleanup_args = ["cleanup"]
```

Any ideas before I reinstall our runner machine?

**Comment by edigaryev** [comment]
> I am getting resource busy error even without shared cache dir 😬

But you have the `--cache-dir` in your configuration, in `config_args`.

As for the `Resource busy`, it looks like it is returned when the the volume is already mounted.

Which Tart version are you using?

**Comment by olejnjak** [comment]
```
~ % brew list  --versions | grep tart
gitlab-tart-executor 1.13.0
tart 2.8.1
```

> As for the Resource busy, it looks like it is returned when the the volume is already mounted.

You mean in the VM?

**Comment by olejnjak** [comment]
Well not really.

```sh
~ % brew list --version | grep tart
gitlab-tart-executor 1.13.0
tart 2.9.0
```

At first I tried without `--dir` and pointing things we want cached on runner to `/Users/admin/cachedir`, still the same Resource busy error. Pretty much the first jobs that got executed failed with that error
```toml
concurrent = 2
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "<...>"
  limit = 2
  url = "<...>"
  id = 840
  token = "<...>"
  token_obtained_at = <...>
  token_expires_at = <...>
  executor = "custom"
  environment = ["MINT_PATH=/Users/admin/cachedir/mint", "MINT_LINK_PATH=/Users/admin/cachedir/mint/bin", "TUIST_CACHE_PATH=/Users/admin/cachedir/TuistCache"]
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.feature_flags]
    FF_RESOLVE_FULL_TLS_CHAIN = true
  [runners.custom]
    config_exec = "gitlab-tart-executor"
    config_args = ["config", "--cache-dir", "/Users/<user>/Gitlab/cache/$CUSTOM_ENV_CI_CONCURRENT_PROJECT_ID"]
    prepare_exec = "gitlab-tart-executor"
    prepare_args = ["prepare", "--memory", "16384"]
    run_exec = "gitlab-tart-executor"
    run_args = ["run"]
    cleanup_exec = "gitlab-tart-executor"
    cleanup_args = ["cleanup"]
```

Then I tried completely without our caching stuff and jobs seem to run. That introduces like extra half an hour to our pipeline.
```toml
concurrent = 2
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "<...>"
  limit = 2
  url = "<...>"
  id = 840
  token = "<...>"
  token_obtained_at = <...>
  token_expires_at = <...>
  executor = "custom"
#  environment = ["MINT_PATH=/Users/admin/cachedir/mint", "MINT_LINK_PATH=/Users/admin/cachedir/mint/bin", "TUIST_CACHE_PATH=/Users/admin/cachedir/TuistCache"]
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.feature_flags]
    FF_RESOLVE_FULL_TLS_CHAIN = true
  [runners.custom]
    config_exec = "gitlab-tart-executor"
    config_args = ["config", "--cache-dir", "/Users/<user>/Gitlab/cache/$CUSTOM_ENV_CI_CONCURRENT_PROJECT_ID"]
    prepare_exec = "gitlab-tart-executor"
    prepare_args = ["prepare", "--memory", "16384"]
    run_exec = "gitlab-tart-executor"
    run_args = ["run"]
    cleanup_exec = "gitlab-tart-executor"
    cleanup_args = ["cleanup"]
```
