### ISSUE TITLE
Support caching

### ISSUE THREAD

**Issue by mschmieder** [cirruslabs/gitlab-tart-executor#9]
To support caching, the runner should mount a cache directory into the VMs using `--dir`

**Comment by edigaryev** [comment]
Hello Matthias! Could you please share the steps you've done to get the local cache working?

For me it results in the following issue when I configure `builds_dir` and `cache_dir` in `~/.gitlab-runner/config.toml`: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27610.

**Comment by mschmieder** [comment]
Hi @edigaryev 

I did test is just a few minutes ago, and it is working fine on the python implementation. I did not do anything special other than making sure that the `config` stage reports the location the cache and builds will be in, which I defined to be `/opt/builds/` and `/opt/cache` [Config Command](https://gitlab.com/schmieder.matthias/gitlab-runner-tart-driver/-/blob/main/gitlab_runner_tart_driver/commands/config.py#L16)

```json
{
  "builds_dir": "/opt/builds",
  "cache_dir": "/opt/cache"
}
```

As I implemented a generic [Volume Mount Feature](https://gitlab.com/schmieder.matthias/gitlab-runner-tart-driver#volume-mounts) I'm using the same mechanism to **mount** and **symlink** the directories. The mount points are given to the `tart` executable via the `--dir` option

After the VM is up, I'm using the following command to create the symlinks [here](https://gitlab.com/schmieder.matthias/gitlab-runner-tart-driver/-/blob/main/gitlab_runner_tart_driver/commands/prepare.py#L248)

```bash
sudo mkdir -p $(dirname {volume.dest}); 
sudo ln -sf '/Volumes/My Shared Files/{volume.name}' {volume.dest}"
```

The `{volume.x}` variables are replaced by the actual mount destination and source.

My test job that looks like this works perfectly fine, placing the caches into the defined directory.

```yaml
run-on-tart:
  image: ventura-xcode-14.3
  tags:
    - tart
  script:
    - echo "This is an artifact" >> artifact.txt
    - mkdir -p vendor/ruby
    - echo "This is an artifact cached" >> vendor/ruby/cache.txt
  cache:
    - key:
        files:
          - artifact.txt
        paths:
          - vendor/ruby
  artifacts:
    paths:
      - artifact.txt
```

This is the `config.toml` I use

```ini
concurrent = 2
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "macmini-m2"
  url = "https://gitlab.com"
  id = XXXXX
  token = "YYYYY"
  token_obtained_at = ZZZZ
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "custom"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.custom]
    config_exec = "/opt/homebrew/bin/gitlab-runner-tart-driver"
    config_args = ["config"]
    config_exec_timeout = 200

    prepare_exec = "/opt/homebrew/bin/gitlab-runner-tart-driver"
    prepare_args = ["prepare", "-x", "/opt/homebrew/bin/tart", "--concurrency", "2", "--auto-resources", "--cache-dir", "/Users/gitlab/gitlab-runner/cache", "--builds-dir", "/Users/gitlab/gitlab-runner/builds"]
    prepare_exec_timeout = 14400

    run_exec = "/opt/homebrew/bin/gitlab-runner-tart-driver"
    run_args = ["run", "-x", "/opt/homebrew/bin/tart"]

    cleanup_exec = "/opt/homebrew/bin/gitlab-runner-tart-driver"
    cleanup_args = ["cleanup", "-x", "/opt/homebrew/bin/tart"]
    cleanup_exec_timeout = 200
```

hope this helps.
